export const LAST_PRICE_PERCENTAGE_24 = "LAST_PRICE_PERCENTAGE_24";
export const GET_ALL_TICKER = "GET_ALL_TICKER";
export const FAVORITE_MARKET = "FAVORITE_MARKET";
export const ALL_ASSETS = "ALL_ASSETS"
